create table product (
    id                 bigint generated by default as identity,
    category           varchar(255),
    count              integer,
    created_at         timestamp,
    description        varchar(255),
    like_count         bigint,
    liked              blob,
    main_image_url     varchar(255),
    name               varchar(255),
    price              integer,
    status             varchar(255),
    updated_at         timestamp,
    view_count         bigint,
    member_id          bigint,
    primary key (id)
);

create table product_image (
    id                 bigint generated by default as identity,
    created_at         timestamp,
    is_main_image      boolean,
    updated_at         timestamp,
    url                varchar(255),
    product_id         bigint,
    primary key (id)
);

alter table product
    add constraint FKnlsnjukov4vm4dv1dw0l438hi
        foreign key (member_id)
            references member;

alter table product_image
    add constraint FK6oo0cvcdtb6qmwsga468uuukk
        foreign key (product_id)
            references product;