create table likes (
    id          bigint generated by default as identity,
    reg_date    timestamp,
    member_id   bigint,
    product_id  bigint,
    primary key (id)
);

alter table likes
    add constraint FKa4vkf1skcfu5r6o5gfb5jf295
        foreign key (member_id)
            references member;

alter table likes
    add constraint FKbt06f6qrlpr663ng2qlb0gvu8
        foreign key (product_id)
            references product;
