create table email_auth (
    id                  bigint generated by default as identity,
    created_date        timestamp not null,
    last_modified_date   timestamp not null,
    auth_token          varchar(255),
    email               varchar(255),
    expire_date         timestamp,
    expired             boolean,
    primary key (id)
);

create table email_message (
    id                  bigint generated by default as identity,
    created_date        timestamp not null,
    last_modified_date   timestamp not null,
    email               varchar(255) not null,
    message             clob not null,
    send                boolean not null,
    status              varchar(255),
    primary key (id)
);