create table notice (
    id                  bigint generated by default as identity,
    created_date        timestamp not null,
    last_modified_date   timestamp not null,
    is_view             boolean,
    message             varchar(255),
    from_member_id      bigint,
    to_member_id        bigint,
    primary key (id)
);

alter table notice
    add constraint FKanbfkpjymwg49fdyb4q62e5w3
        foreign key (from_member_id)
            references member;

alter table notice
    add constraint FK475wfcm95si0x8rrt6a7ard72
        foreign key (to_member_id)
            references member;
